comment_width = 100
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "One"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
